//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerencsejatek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Szelveny_Id { get; set; }
        public int t01 { get; set; }
        public int t02 { get; set; }
        public int t03 { get; set; }
        public int t04 { get; set; }
        public int t05 { get; set; }
    }
}
